steps:
  - name: node:22
    dir: Frontend
    env:
      - VITE_API_BASE_URL=${_VITE_API_BASE_URL}
    script: |
      npm ci
      npm run build
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -m
      - rsync
      - -r
      - Frontend/dist
      - gs://${_FRONTEND_BUCKET}

substitutions:
  _VITE_API_BASE_URL: https://todo-api-48417328230.europe-west10.run.app
  _FRONTEND_BUCKET: cloud-todo

options:
  logging: CLOUD_LOGGING_ONLY
