steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Backend/Dockerfile
      - --build-arg
      - DATABASE_URL=postgresql://user:pass@localhost:5432/postgres
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$SHORT_SHA
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$SHORT_SHA
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$SHORT_SHA
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-secrets
      - DATABASE_URL=${_DATABASE_URL_SECRET}:latest

substitutions:
  _REGION: europe-west3
  _AR_REPO: todo-app
  _SERVICE_NAME: todo-api
  _DATABASE_URL_SECRET: supabase-database-url

options:
  logging: CLOUD_LOGGING_ONLY
